### ISSUE TITLE
Remove movie from the toWatchPlaylist

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#86]
Behavior
=======
when user hits `<DEL>` or right-click delete (only on playlist mode) the movie is removed from the list

**Comment by sebtouze** [comment]
I have to change a bit the way I've done the remofe-from-playlist action to add the <DEL> shortcut.

**Comment by sebtouze** [comment]
Well, I reopen because the way things are done is strange....
When in To Watch, you delete from to Watch list with <DEL> and when outside from To Watch, you DELETE a file with <DEL>.... I think this may be confusing for the user isn't it ? 

Furthermore, the QMessageBox is a critical one, I think removing a movie from a playlist is not that critical, a information or Warning is enough isn't it ? ;)

**Comment by ochurlaud** [comment]
I don't agree: 

* the user won't find it strange because if you want to delete a movie from somewher, you delete it. The action is the same, the result different. But the menu has another name too depending on the context
* it prevent us to repeat to much code

I agree for the type of box but it's a minor modification.

Waiting for your answer...

**Comment by ochurlaud** [comment]
@sebtouze tell me if you agree so that we can close it (or not)

**Comment by sebtouze** [comment]
I still find this confusing, as the `<DEL>` act once on files and once on playlist, which is very different. 
Furthermore, why do we not allow to delete a file when in to Watch playlist ?
